version: '3'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rapla_db
      MYSQL_USER: rapla_db_user
      MYSQL_PASSWORD: bR5be763wU
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      #MYSQL_ROOT_PASSWORD: password
    volumes:
      - my-db:/var/lib/mysql

  web:
    build: rapla_tomcat
    restart: unless-stopped
    expose:
      - '8080'
    depends_on:
      - db
    # Forward to host port (devlopment purpose)
    ports:
      - '8080:8080'

# Names our volume
volumes:
  my-db:
